/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PatientRouteImport } from './routes/patient'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientIndexRouteImport } from './routes/patient.index'
import { Route as DoctorIndexRouteImport } from './routes/doctor.index'
import { Route as PatientSettingsRouteImport } from './routes/patient.settings'
import { Route as PatientMedicationsRouteImport } from './routes/patient.medications'
import { Route as PatientLabsRouteImport } from './routes/patient.labs'
import { Route as PatientGlucoseRouteImport } from './routes/patient.glucose'
import { Route as PatientChatRouteImport } from './routes/patient.chat'
import { Route as PatientAppointmentsRouteImport } from './routes/patient.appointments'
import { Route as DoctorScheduleRouteImport } from './routes/doctor.schedule'
import { Route as DoctorPatientIdRouteImport } from './routes/doctor.patient.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientRoute = PatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientIndexRoute = PatientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientRoute,
} as any)
const DoctorIndexRoute = DoctorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DoctorRoute,
} as any)
const PatientSettingsRoute = PatientSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PatientRoute,
} as any)
const PatientMedicationsRoute = PatientMedicationsRouteImport.update({
  id: '/medications',
  path: '/medications',
  getParentRoute: () => PatientRoute,
} as any)
const PatientLabsRoute = PatientLabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => PatientRoute,
} as any)
const PatientGlucoseRoute = PatientGlucoseRouteImport.update({
  id: '/glucose',
  path: '/glucose',
  getParentRoute: () => PatientRoute,
} as any)
const PatientChatRoute = PatientChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => PatientRoute,
} as any)
const PatientAppointmentsRoute = PatientAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => PatientRoute,
} as any)
const DoctorScheduleRoute = DoctorScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorPatientIdRoute = DoctorPatientIdRouteImport.update({
  id: '/patient/$id',
  path: '/patient/$id',
  getParentRoute: () => DoctorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/doctor': typeof DoctorRouteWithChildren
  '/login': typeof LoginRoute
  '/patient': typeof PatientRouteWithChildren
  '/signup': typeof SignupRoute
  '/doctor/schedule': typeof DoctorScheduleRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/chat': typeof PatientChatRoute
  '/patient/glucose': typeof PatientGlucoseRoute
  '/patient/labs': typeof PatientLabsRoute
  '/patient/medications': typeof PatientMedicationsRoute
  '/patient/settings': typeof PatientSettingsRoute
  '/doctor/': typeof DoctorIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/doctor/patient/$id': typeof DoctorPatientIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/doctor/schedule': typeof DoctorScheduleRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/chat': typeof PatientChatRoute
  '/patient/glucose': typeof PatientGlucoseRoute
  '/patient/labs': typeof PatientLabsRoute
  '/patient/medications': typeof PatientMedicationsRoute
  '/patient/settings': typeof PatientSettingsRoute
  '/doctor': typeof DoctorIndexRoute
  '/patient': typeof PatientIndexRoute
  '/doctor/patient/$id': typeof DoctorPatientIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/doctor': typeof DoctorRouteWithChildren
  '/login': typeof LoginRoute
  '/patient': typeof PatientRouteWithChildren
  '/signup': typeof SignupRoute
  '/doctor/schedule': typeof DoctorScheduleRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/chat': typeof PatientChatRoute
  '/patient/glucose': typeof PatientGlucoseRoute
  '/patient/labs': typeof PatientLabsRoute
  '/patient/medications': typeof PatientMedicationsRoute
  '/patient/settings': typeof PatientSettingsRoute
  '/doctor/': typeof DoctorIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/doctor/patient/$id': typeof DoctorPatientIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/doctor'
    | '/login'
    | '/patient'
    | '/signup'
    | '/doctor/schedule'
    | '/patient/appointments'
    | '/patient/chat'
    | '/patient/glucose'
    | '/patient/labs'
    | '/patient/medications'
    | '/patient/settings'
    | '/doctor/'
    | '/patient/'
    | '/doctor/patient/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/doctor/schedule'
    | '/patient/appointments'
    | '/patient/chat'
    | '/patient/glucose'
    | '/patient/labs'
    | '/patient/medications'
    | '/patient/settings'
    | '/doctor'
    | '/patient'
    | '/doctor/patient/$id'
  id:
    | '__root__'
    | '/'
    | '/doctor'
    | '/login'
    | '/patient'
    | '/signup'
    | '/doctor/schedule'
    | '/patient/appointments'
    | '/patient/chat'
    | '/patient/glucose'
    | '/patient/labs'
    | '/patient/medications'
    | '/patient/settings'
    | '/doctor/'
    | '/patient/'
    | '/doctor/patient/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DoctorRoute: typeof DoctorRouteWithChildren
  LoginRoute: typeof LoginRoute
  PatientRoute: typeof PatientRouteWithChildren
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/': {
      id: '/patient/'
      path: '/'
      fullPath: '/patient/'
      preLoaderRoute: typeof PatientIndexRouteImport
      parentRoute: typeof PatientRoute
    }
    '/doctor/': {
      id: '/doctor/'
      path: '/'
      fullPath: '/doctor/'
      preLoaderRoute: typeof DoctorIndexRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/patient/settings': {
      id: '/patient/settings'
      path: '/settings'
      fullPath: '/patient/settings'
      preLoaderRoute: typeof PatientSettingsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/medications': {
      id: '/patient/medications'
      path: '/medications'
      fullPath: '/patient/medications'
      preLoaderRoute: typeof PatientMedicationsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/labs': {
      id: '/patient/labs'
      path: '/labs'
      fullPath: '/patient/labs'
      preLoaderRoute: typeof PatientLabsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/glucose': {
      id: '/patient/glucose'
      path: '/glucose'
      fullPath: '/patient/glucose'
      preLoaderRoute: typeof PatientGlucoseRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/chat': {
      id: '/patient/chat'
      path: '/chat'
      fullPath: '/patient/chat'
      preLoaderRoute: typeof PatientChatRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/appointments': {
      id: '/patient/appointments'
      path: '/appointments'
      fullPath: '/patient/appointments'
      preLoaderRoute: typeof PatientAppointmentsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/doctor/schedule': {
      id: '/doctor/schedule'
      path: '/schedule'
      fullPath: '/doctor/schedule'
      preLoaderRoute: typeof DoctorScheduleRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/patient/$id': {
      id: '/doctor/patient/$id'
      path: '/patient/$id'
      fullPath: '/doctor/patient/$id'
      preLoaderRoute: typeof DoctorPatientIdRouteImport
      parentRoute: typeof DoctorRoute
    }
  }
}

interface DoctorRouteChildren {
  DoctorScheduleRoute: typeof DoctorScheduleRoute
  DoctorIndexRoute: typeof DoctorIndexRoute
  DoctorPatientIdRoute: typeof DoctorPatientIdRoute
}

const DoctorRouteChildren: DoctorRouteChildren = {
  DoctorScheduleRoute: DoctorScheduleRoute,
  DoctorIndexRoute: DoctorIndexRoute,
  DoctorPatientIdRoute: DoctorPatientIdRoute,
}

const DoctorRouteWithChildren =
  DoctorRoute._addFileChildren(DoctorRouteChildren)

interface PatientRouteChildren {
  PatientAppointmentsRoute: typeof PatientAppointmentsRoute
  PatientChatRoute: typeof PatientChatRoute
  PatientGlucoseRoute: typeof PatientGlucoseRoute
  PatientLabsRoute: typeof PatientLabsRoute
  PatientMedicationsRoute: typeof PatientMedicationsRoute
  PatientSettingsRoute: typeof PatientSettingsRoute
  PatientIndexRoute: typeof PatientIndexRoute
}

const PatientRouteChildren: PatientRouteChildren = {
  PatientAppointmentsRoute: PatientAppointmentsRoute,
  PatientChatRoute: PatientChatRoute,
  PatientGlucoseRoute: PatientGlucoseRoute,
  PatientLabsRoute: PatientLabsRoute,
  PatientMedicationsRoute: PatientMedicationsRoute,
  PatientSettingsRoute: PatientSettingsRoute,
  PatientIndexRoute: PatientIndexRoute,
}

const PatientRouteWithChildren =
  PatientRoute._addFileChildren(PatientRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DoctorRoute: DoctorRouteWithChildren,
  LoginRoute: LoginRoute,
  PatientRoute: PatientRouteWithChildren,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
